version: "3"

volumes:
  DB-lolcal-library-postgres:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "DB-lolcal-library-postgres:/var/lib/postgresql/data"
    env_file: .env