# Generated by Django 3.2.7 on 2021-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210919_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter the book's language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
