# Generated by Django 3.2.7 on 2022-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='detail',
        ),
        migrations.AddField(
            model_name='log',
            name='operation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
