# Generated by Django 3.2.7 on 2022-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220616_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
